services:
  vfl-feature-selection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vfl-feature-selection
    volumes:
      - ./Data:/app/Data:ro
      - ./results:/app/results
      - ./fedsdg:/app/fedsdg
      - ./PSO:/app/PSO
      - ./VF-PS:/app/VF-PS
      - ./vfl-master@73591d69c04-2:/app/vfl-master@73591d69c04-2
    working_dir: /app
    network_mode: "host"
    stdin_open: true
    tty: true
